### ISSUE TITLE
[FR] Navigation Layout

### ISSUE THREAD

**Issue by rileyhawk1417** [fred-juma/iGymHealth#10]
The navigation layout for the app.
This allows the user to visit certain parts of the app at with ease.
A bottom navigation layout is suggested for the app to work with.
The suggestion is to have two layouts, a bottom navigation layout for the main features. Then tab layout for the extra features.

### Bottom Navigation Screens:

- [x] Dashboard
    - Displays cards:
        - Workouts done for the day.
        - Articles Saved.
        - Motivational Quote?
- [x] Settings
- [x] Health
    - [x] Physical Health
    - [x] Mental Health
- [x] Favourites 
    - [x] Articles
    - [x] Blogs
- [x] Blogs/Articles
    - [x] Tips

### Tab Navigation Screens:

- [x] Health
    - [x] Physical Health
    - [x] Mental Health
    - [x] Dieting Suggestions
- [x] Favourites 
    - [x] Articles
    - [x] Blogs
- [x] Blogs/Articles
    - [x] Tips

**Comment by LawrenceMmethi** [comment]
I have not being added  to a group yet...
